import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import Dashboard from "@/components/dashboard";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { StyledComponentsRegistry } from "@/components/styled-registry";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Human-in-the-loop",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect("/api/auth/signin");
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Dashboard serverSession={session}>{children}</Dashboard>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
