name: Release workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create mocked .env.local with required variables
        run: |
          echo MONGODB_URI=mongodb://mongo                 > .env.local
          echo MONGODB_DB=mongodb                          >> .env.local
          echo ENCRYPTION_KEY=encryption_key               >> .env.local
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1
      - run: bun install
      - run: bun run build
      - run: bun run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
